In [5]:
import pandas as pd
base = pd.read_excel("Atividade_Tabela_Freq.xlsx")
base

    Turma     Gênero  Idade  ALTURA  PESO     REDES  TEMPO
0      1D  Masculino     12     147    62    TikTok      6
1      1D  Masculino     11     151    70    TikTok      1
2      1D  Masculino     12     156    61    TikTok      9
3      1D  Masculino     11     147    71    TikTok     11
4      1D  Masculino     13     155    76    TikTok     12
..    ...        ...    ...     ...   ...       ...    ...
295    1E  Masculino     12     157    79  Whatsapp     67
296    1E  Masculino     12     156    79  Whatsapp     67
297    1E  Masculino     13     155    57  Whatsapp     67
298    1E  Masculino     12     151    75  Whatsapp     67
299    1E  Masculino     12     157    54  Whatsapp     61

[300 rows x 7 columns]

In [6]:
rede = base["REDES"].value_counts()
rede

REDES
TikTok       164
Whatsapp     102
Instagram     34
Name: count, dtype: int64

In [8]:
total = rede.sum()
print(total)

300

In [9]:
redes_df = pd.DataFrame(rede)
redes_df

           count
REDES
TikTok       164
Whatsapp     102
Instagram     34

In [10]:
redes_df["Frequencia Relativa"] = redes_df["count"]/total
redes_df["Frequencia Relativa %"] = redes_df["Frequencia Relativa"]/total
redes_df

           count  Frequencia Relativa  Frequencia Relativa %
REDES
TikTok       164             0.546667               0.001822
Whatsapp     102             0.340000               0.001133
Instagram     34             0.113333               0.000378