In [32]:
import pandas as pd

In [33]:
base = pd.read_excel("Resposta_Musical.xlsx")
base

    ID_Aluno Genero_Musical
0          1            Pop
1          2         Gospel
2          3     Eletrônica
3          4          K-pop
4          5         Reggae
..       ...            ...
95        96          Forró
96        97        Hip Hop
97        98           Funk
98        99           Funk
99       100      Sertanejo

[100 rows x 2 columns]

In [34]:
genero = base["Genero_Musical"].value_counts()
genero

Genero_Musical
Eletrônica    12
Reggae        11
Pagode        11
Gospel         9
Rap            8
Sertanejo      8
Jazz           6
Funk           6
Clássica       6
Forró          6
MPB            5
Pop            4
K-pop          4
Rock           3
Hip Hop        1
Name: count, dtype: int64

In [36]:
total = genero.sum()
print(total)

100

In [38]:
genero_df = pd.DataFrame(genero)
genero_df

                count
Genero_Musical
Eletrônica         12
Reggae             11
Pagode             11
Gospel              9
Rap                 8
Sertanejo           8
Jazz                6
Funk                6
Clássica            6
Forró               6
MPB                 5
Pop                 4
K-pop               4
Rock                3
Hip Hop             1

Criar Frequencia Relativa

In [ ]:
genero_df["Frequencia Relativa"] = genero_df["count"]/total
genero_df["Frequencia Relativa %"] = genero_df["Frequencia Relativa"]/total
genero_df

                count    FR  Frequencia Relativa  Frequencia Relativa %
Genero_Musical
Eletrônica         12  0.12                 0.12                 0.0012
Reggae             11  0.11                 0.11                 0.0011
Pagode             11  0.11                 0.11                 0.0011
Gospel              9  0.09                 0.09                 0.0009
Rap                 8  0.08                 0.08                 0.0008
Sertanejo           8  0.08                 0.08                 0.0008
Jazz                6  0.06                 0.06                 0.0006
Funk                6  0.06                 0.06                 0.0006
Clássica            6  0.06                 0.06                 0.0006
Forró               6  0.06                 0.06                 0.0006
MPB                 5  0.05                 0.05                 0.0005
Pop                 4  0.04                 0.04                 0.0004
K-pop               4  0.04                 0.04                 0.0004
Rock                3  0.03                 0.03                 0.0003
Hip Hop             1  0.01                 0.01                 0.0001