In [2]:
import pandas as pd

Exercicio1-Ler 5 linhas

In [4]:
base = pd.read_excel("Atividade_Tabela_Freq.xlsx")
base.head(5)

  Turma     Gênero  Idade  ALTURA  PESO   REDES  TEMPO
0    1D  Masculino     12     147    62  TikTok      6
1    1D  Masculino     11     151    70  TikTok      1
2    1D  Masculino     12     156    61  TikTok      9
3    1D  Masculino     11     147    71  TikTok     11
4    1D  Masculino     13     155    76  TikTok     12

Exercicio2-FA

In [5]:
redes = base["REDES"].value_counts()
redes

REDES
TikTok       164
Whatsapp     102
Instagram     34
Name: count, dtype: int64

Exercicio3-TotalREspostas

In [6]:
total = redes.sum()
total

np.int64(300)

Exercicio4-FR%

In [ ]:
fr = (redes/total)*100
fr

REDES
TikTok       54.666667
Whatsapp     34.000000
Instagram    11.333333
Name: count, dtype: float64

Exercicio5-Tabela Completa

In [12]:
df = pd.DataFrame(redes.reset_index().values, columns=["Rede Social","FA"])
df["FR"] = df["FA"]/total
df["FR%"] = df["FR"]*100
df

  Rede Social   FA        FR        FR%
0      TikTok  164  0.546667  54.666667
1    Whatsapp  102      0.34       34.0
2   Instagram   34  0.113333  11.333333

-------------------------------------------------------------------------------

Exercicio REsposta Musical

6

In [18]:
baseM = pd.read_excel("Resposta_Musical.xlsx")
genero = baseM["Genero_Musical"].value_counts()
totalM = genero.sum()
dfM = pd.DataFrame(genero.reset_index().values,columns=["Genero","FA"])
dfM["FR"] =dfM["FA"]/totalM
dfM["FR%"] = dfM["FR"]*100
dfM

        Genero  FA    FR   FR%
0   Eletrônica  12  0.12  12.0
1       Reggae  11  0.11  11.0
2       Pagode  11  0.11  11.0
3       Gospel   9  0.09   9.0
4          Rap   8  0.08   8.0
5    Sertanejo   8  0.08   8.0
6         Jazz   6  0.06   6.0
7         Funk   6  0.06   6.0
8     Clássica   6  0.06   6.0
9        Forró   6  0.06   6.0
10         MPB   5  0.05   5.0
11         Pop   4  0.04   4.0
12       K-pop   4  0.04   4.0
13        Rock   3  0.03   3.0
14     Hip Hop   1  0.01   1.0