In [1]:
pip install ipykernel

Requirement already satisfied: ipykernel in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (7.2.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (9.10.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (26.0)
Requirement already satisfied: psutil>=5.7 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (6.5.4)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel) (0.8.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from jupyter-client>=8.8.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.2)
Requirement already satisfied: six>=1.5 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.8.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\20260167-ieg\appdata\roaming\python\python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Aula 1 - Importando Pacotes e Tabelas de Frequencia

In [2]:
import pandas as pd

Importando a base de dados.

In [3]:
base = pd.read_excel("Resposta_Musical.xlsx")

Lendo as 10 primeiras linhas

In [4]:
base.head(10)

   ID_Aluno Genero_Musical
0         1            Pop
1         2         Gospel
2         3     Eletrônica
3         4          K-pop
4         5         Reggae
5         6            MPB
6         7            Rap
7         8     Eletrônica
8         9         Pagode
9        10         Gospel

Calcular a frequência absoluta

In [5]:
genero = base["Genero_Musical"].value_counts()

Podemos verificar a estrutura dos dados

In [6]:
genero

Genero_Musical
Eletrônica    12
Reggae        11
Pagode        11
Gospel         9
Rap            8
Sertanejo      8
Jazz           6
Funk           6
Clássica       6
Forró          6
MPB            5
Pop            4
K-pop          4
Rock           3
Hip Hop        1
Name: count, dtype: int64

Colocando o total de participantes

In [7]:
total = genero.sum()
print(total)

100

Quero transformar em um dataframe. Desse modo, podemos trabalhar com mais liberdade com os dados

In [8]:
df = pd.DataFrame(genero)
df

                count
Genero_Musical
Eletrônica         12
Reggae             11
Pagode             11
Gospel              9
Rap                 8
Sertanejo           8
Jazz                6
Funk                6
Clássica            6
Forró               6
MPB                 5
Pop                 4
K-pop               4
Rock                3
Hip Hop             1

Criar uma nova coluna com a frequência relativa. Lembre que a frequência relativa é dada pela seguinte relação $Frequência_Relativa = \frac{Frequência_Relativa}{Total}$

In [9]:
df["Freq_Relativa"] = df["count"]/ total 
df

                count  Freq_Relativa
Genero_Musical
Eletrônica         12           0.12
Reggae             11           0.11
Pagode             11           0.11
Gospel              9           0.09
Rap                 8           0.08
Sertanejo           8           0.08
Jazz                6           0.06
Funk                6           0.06
Clássica            6           0.06
Forró               6           0.06
MPB                 5           0.05
Pop                 4           0.04
K-pop               4           0.04
Rock                3           0.03
Hip Hop             1           0.01

Criar uma coluna com para frequência relativa percentual.

In [10]:
df["Freq_Relativa_%"] = df["Freq_Relativa"]*100
df

                count  Freq_Relativa  Freq_Relativa_%
Genero_Musical
Eletrônica         12           0.12             12.0
Reggae             11           0.11             11.0
Pagode             11           0.11             11.0
Gospel              9           0.09              9.0
Rap                 8           0.08              8.0
Sertanejo           8           0.08              8.0
Jazz                6           0.06              6.0
Funk                6           0.06              6.0
Clássica            6           0.06              6.0
Forró               6           0.06              6.0
MPB                 5           0.05              5.0
Pop                 4           0.04              4.0
K-pop               4           0.04              4.0
Rock                3           0.03              3.0
Hip Hop             1           0.01              1.0